Portfolio work section & About
AbbasSarwar/Abbas-Portfolio pull request #2
Opened 2023-02-16 16:15 UTC by AbbasSarwar

**Features more:**
* added images
* colors 
* icons 
* Fonts family *Poppins*
* 5 sections

**Bugs:**
* linter errors fixed
* styles fixed
* multiple elements fixed

**files**
* HTML
* CSS
* Image files
* Linter files
* Readme

2023-02-16 22:04 UTC, AdnanOlarmmi requested changes
Hi @AbbasSarwar, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Professional Readme.
- Design is Responsive.
- 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 22:04 UTC, AdnanOlarmmi commented on index.html
> +            <div class="work-details">
- [  ] Nice work putting each of the work sections in a `section` tag. However, kindly note that all work sections is supposed to be in a single tag, preferably `main` for semantic reasons, arranged with grid. then the content of each individual work-section tag arranged with flex-box 😀

2023-02-16 22:04 UTC, AdnanOlarmmi commented on index.html
> +
- [ ] [OPTIONAL] I suggest that at the top of the `main` tag, there should be a header, written in an `h1` tag for SEOs, describing what that section is for, having a phrase like "My Recent Works", depicting what the container is for and also enhancing SEOs. 🙂

2023-02-16 22:04 UTC, AdnanOlarmmi commented on index.html
> +            </div>
- [ ] Nice work adding the button, but however the styling of the button is almost pixel-perfect, you implemented the enable button properly except for other effect properties, like the hover effect and the likes, this will result in you having an utmost pixel-perfect design.

- Your design
- on enabled
<img width="97" alt="unhover" src="https://user-images.githubusercontent.com/41163571/219494812-6a8d019c-2bf2-41c0-b217-c97d2108712f.png">
- on hover
<img width="102" alt="hover" src="https://user-images.githubusercontent.com/41163571/219494727-164fc655-e99a-4941-815b-966499f08be8.png">

- Figma design

<img width="400" alt="right" src="https://user-images.githubusercontent.com/41163571/219494963-adfe8790-b0e5-4098-b021-8aecfc5a301c.png">

2023-02-16 22:04 UTC, AdnanOlarmmi commented on index.html
> +                <button>Get my resume</button>
- [ ] Kindly effect the button properties to the `Get my resume` button accordingly 😀.

2023-02-16 22:04 UTC, AdnanOlarmmi commented on index.html
> +        </section>
- [ ] Please, kindly ensure that **all** your design specifications (padding, margin, font-size, font-weight, border-radius and so on) align with that of Figma as much as possible, So as to have a pixel perfect design as you're going to soon be doing in your future job.

- Your design
<img width="156" alt="wrong" src="https://user-images.githubusercontent.com/41163571/219496791-244b907e-6793-40c6-b823-ae840bd7db62.png">

- Figma design
<img width="266" alt="right" src="https://user-images.githubusercontent.com/41163571/219496881-ca4db9ca-5334-4190-9ea8-5f457ab01e25.png">

2023-02-17 08:29 UTC, emmiiorji requested changes
Hi @AbbasSarwar, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 08:29 UTC, emmiiorji commented on index.html
> +                    <li><a href="https://github.com/AbbasSarwar" class="connect"><img src="image-resources/Github.png" alt="Github logo"></a></li>
You seem to have made an error linked the image for the LinkedIn logo. The `linkedIn.png` does not exist in the `image-resources` folder.

Your design:
![image](https://user-images.githubusercontent.com/20554583/219592514-db69fc3a-72af-473a-aa4a-08afe85fb04f.png)

2023-02-17 09:30 UTC, adel-gu approved these changes
# STATUS: APPROVED 🟢 

Hi @AbbasSarwar 👋🏼  

Your project is **APPROVED**! 👏✨ well done following the previous reviewer's suggestions 😎, However, I left some **OPTIONAL** changes that will help your project stand out more 🚀, **but In general There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉** 

## Highlights
- Linkedin icon displayed 👍🏼 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 09:30 UTC, adel-gu commented on README.md
> +
- **[OPTIONAL]** the live demo should lead to a working website that is deployed🚀, in your case is not really necessary for the current milestone, you will have the chance to implement it in the coming lessons 😎

2023-02-17 09:30 UTC, adel-gu commented on README.md
> +> Mention all of the collaborators of this project.
- **[OPTIONAL]** This is a guiding comment please consider removing all comments after filling out its related section.

2023-02-17 09:30 UTC, adel-gu commented on README.md
> +> Give credit to everyone who inspired your codebase.
- **[OPTIONAL]** Kindly consider removing this comment as well 💪👏

2023-02-17 09:30 UTC, adel-gu commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- **[OPTIONAL]** The absence of the MIT.md file in your repo caused this link to be broken, please add the license file to your repo.

2023-02-17 09:30 UTC, adel-gu commented on style.css
> +  }
- **[OPTIONAL]** the button style state is different from the Figma file, as required ensure to duplicate the design as much as possible ✨

### Your Design
![image](https://user-images.githubusercontent.com/68030297/219604231-39474ba9-9a0d-4996-8ff1-f6af472aeed4.png)


### Figma Design
![image](https://user-images.githubusercontent.com/68030297/219604335-33730f0d-a9e3-47a5-ab29-e54999fcabd0.png)

2023-02-17 09:30 UTC, adel-gu commented on index.html
> +                <li><a href="#"><i class="fa-brands fa-css3-alt"></i> CSS</a></li>
- **[OPTIONAL]** As suggested in the project requirement to follow the design system as much as possible I highly recommend using the assets from the Figma design for the skills section.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/219605452-9511ab1a-57cd-426d-8619-986e9e2191b1.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/219605407-77e3f523-acd3-4be8-afbb-44599d4449a4.png)

2023-02-17 09:38 UTC, merged